### ISSUE TITLE
[HELP WANTED] Working on browser

### ISSUE THREAD

**Issue by ospfranco** [myspace/page-previewer#6]
Hey, can I use this module straight from the browser or must it be called from a server to avoid CORS issues?

**Comment by jb-reefer** [comment]
I can't get this to run outside of node - webpack throws a ton of errors when trying to include it in a react project. Too bad.

**Comment by ospfranco** [comment]
this project seems to be deprecated, but because of CORS it will basically never run out of node or non sandboxed environments (ex: react-native).
